# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='model_pic',
            field=models.ImageField(blank=True, default='blog/images/relax.png', null=True, upload_to='images/'),
        ),
    ]
